### ISSUE TITLE
ConnectionError on configure event

### ISSUE THREAD

**Issue by gruyaume** [gruyaume/eupf-k8s-operator#18]
### Bug Description

ConnectionError on configure event

### To Reproduce

juju deploy

### Environment

microk8s

### Relevant log output

```shell
unit-eupf-k8s-0: 15:23:34 ERROR unit.eupf-k8s/0.juju-log Failed to execute command. File not found.
unit-eupf-k8s-0: 15:23:34 ERROR unit.eupf-k8s/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-eupf-k8s-0/charm/./src/charm.py", line 422, in <module>
    ops.main(EupfK8SOperatorCharm)  # type: ignore
  File "/var/lib/juju/agents/unit-eupf-k8s-0/charm/venv/ops/main.py", line 560, in __call__
    return main(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-eupf-k8s-0/charm/venv/ops/main.py", line 548, in main
    manager.run()
  File "/var/lib/juju/agents/unit-eupf-k8s-0/charm/venv/ops/main.py", line 527, in run
    self._emit()
  File "/var/lib/juju/agents/unit-eupf-k8s-0/charm/venv/ops/main.py", line 516, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-eupf-k8s-0/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-eupf-k8s-0/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-eupf-k8s-0/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-eupf-k8s-0/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-eupf-k8s-0/charm/./src/charm.py", line 172, in _configure
    self._create_default_route()
  File "/var/lib/juju/agents/unit-eupf-k8s-0/charm/./src/charm.py", line 218, in _create_default_route
    self._exec_command_in_workload(
  File "/var/lib/juju/agents/unit-eupf-k8s-0/charm/./src/charm.py", line 193, in _exec_command_in_workload
    process = self._container.exec(
  File "/var/lib/juju/agents/unit-eupf-k8s-0/charm/venv/ops/model.py", line 2824, in exec
    return self._pebble.exec(
  File "/var/lib/juju/agents/unit-eupf-k8s-0/charm/venv/ops/pebble.py", line 2748, in exec
    resp = self._request('POST', '/v1/exec', body=body)
  File "/var/lib/juju/agents/unit-eupf-k8s-0/charm/venv/ops/pebble.py", line 1859, in _request
    response = self._request_raw(method, path, query, headers, data)
  File "/var/lib/juju/agents/unit-eupf-k8s-0/charm/venv/ops/pebble.py", line 1912, in _request_raw
    raise ConnectionError(
ops.pebble.ConnectionError: Could not connect to Pebble: socket not found at '/charm/containers/eupf/pebble.socket' (container restarted?)
```

**Comment by gruyaume** [comment]
Similar issue:

```
unit-eupf-0: 17:20:56 ERROR unit.eupf/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-eupf-0/charm/./src/charm.py", line 422, in <module>
    ops.main(EupfK8SOperatorCharm)  # type: ignore
  File "/var/lib/juju/agents/unit-eupf-0/charm/venv/ops/main.py", line 560, in __call__
    return main(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-eupf-0/charm/venv/ops/main.py", line 548, in main
    manager.run()
  File "/var/lib/juju/agents/unit-eupf-0/charm/venv/ops/main.py", line 527, in run
    self._emit()
  File "/var/lib/juju/agents/unit-eupf-0/charm/venv/ops/main.py", line 516, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-eupf-0/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-eupf-0/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-eupf-0/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-eupf-0/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-eupf-0/charm/./src/charm.py", line 179, in _configure
    self._configure_pebble(restart=restart)
  File "/var/lib/juju/agents/unit-eupf-0/charm/./src/charm.py", line 336, in _configure_pebble
    self._container.replan()
  File "/var/lib/juju/agents/unit-eupf-0/charm/venv/ops/model.py", line 2211, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-eupf-0/charm/venv/ops/pebble.py", line 1993, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-eupf-0/charm/venv/ops/pebble.py", line 2090, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "eupf" (cannot start service: exited quickly with code 1)

```
